name: para_tir
description: "Para Tir - Sky Defense Kids Game"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.2
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.0
  share_plus: ^10.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/icon.png
    - assets/audio/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/icon.png
  adaptive_icon_background: "#4A00E0"
  adaptive_icon_foreground: assets/images/logo.png

flutter_native_splash:
  color: "#2A085C"
  image: assets/images/logo.png
  android: true
  ios: true